run:
  timeout: 3m
  tests: false
linters:
  enable:
    - govet
    - gofmt
    - staticcheck
    - gosimple
    - ineffassign
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
