version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: embolsadora
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/embolsadora?sslmode=disable
      REDIS_ADDR: redis:6379
      APP_ENV: dev
      AUTH_JWT_ISSUER: embolsadora
      AUTH_JWT_PUBLIC: __placeholder__
      AUTH_JWT_PRIVATE: __placeholder__
    ports:
      - "8080:8080"
