name: Postman - Newman

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest
    env:
      STAGING_BASE_URL: ${{ vars.STAGING_BASE_URL || 'https://staging.example.com' }}
      POSTMAN_AUTH_TOKEN: ${{ secrets.POSTMAN_AUTH_TOKEN || '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install newman
        run: npm i -g newman

      - name: Prepare env file
        run: |
          cat > postman/_ci_env.postman_environment.json <<'EOF'
          {
            "name": "CI-Staging",
            "_postman_variable_scope": "environment",
            "values": [
              { "key": "base_url", "value": "${{ env.STAGING_BASE_URL }}", "enabled": true },
              { "key": "auth_token", "value": "${{ env.POSTMAN_AUTH_TOKEN }}", "enabled": true }
            ]
          }
          EOF

      - name: Run Newman
        run: |
          newman run "postman/api-embolsadora-api.postman_collection.json" \
            -e "postman/_ci_env.postman_environment.json" \
            --reporters cli \
            --timeout-request 10000
